apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: workshop
type: Opaque
data:
  mongo-root-username: YWRtaW4= # "admin" in base64
  mongo-root-password: dGVzdHBhc3MxMjM= # "testpass123" in base64
